#!/usr/bin/env bash
# Bundle every .ttf / .otf / .ttc in assets/fonts/ into the binary so
# the exe is self-contained — no `fonts/` folder needed at runtime.
#
# Approach: emit a tiny .S file that uses `.incbin` to pull each font
# into the .rodata section, exposing start/end symbols. A matching .h
# declares the symbols and lists each font for the picker. This is far
# cheaper to compile than a 13MB hex-encoded C array (a single .incbin
# is ~instant; a hex array is multi-megabyte text the preprocessor has
# to parse).
#
# Per-font symbols:
#   _rbterm_font_<ident>_start    (data pointer)
#   _rbterm_font_<ident>_end      (one-past-the-end pointer)
# Display names strip the extension and any -Regular suffix.
set -euo pipefail
src_dir="${1:-assets/fonts}"
out_h="${2:-src/fonts_embedded.h}"
out_s="${3:-src/fonts_embedded.S}"
out_rc="${4:-src/fonts_embedded.rc}"
out_winc="${5:-src/fonts_embedded_win.c}"

emit_empty() {
    cat > "$out_h" <<'EOF'
/* AUTO-GENERATED by tools/gen_fonts.sh (no fonts present). */
#pragma once
typedef struct {
    const char *name;
    const char *ext;            /* "ttf" / "otf" / "ttc" */
    const unsigned char *data;
    unsigned int data_size;
} EmbeddedFont;
static const EmbeddedFont k_embedded_fonts[1] = { {"", "", 0, 0} };
static const int k_embedded_font_count = 0;
EOF
    cat > "$out_s" <<'EOF'
/* AUTO-GENERATED by tools/gen_fonts.sh (no fonts present). */
EOF
}

if [[ ! -d "$src_dir" ]]; then
    emit_empty
    exit 0
fi

display_name() {
    local f="$1"
    f="${f##*/}"
    f="${f%.[oOtT][tT][fFcC]}"
    f="${f%-Regular}"
    f="${f%-regular}"
    echo "$f"
}

c_ident() {
    local f
    f=$(basename "$1")
    echo "${f//[^A-Za-z0-9]/_}"
}

# Apple's clang assembler prefixes C globals with an underscore on
# Mach-O; on ELF (Linux) it doesn't. We emit the macro-friendly form
# and let the assembler / linker resolve.
case "$(uname -s)" in
    Darwin) sym_pfx="_" ;;
    *)      sym_pfx=""  ;;
esac

# Collect files in stable order.
files=$(ls "$src_dir"/*.ttf "$src_dir"/*.otf "$src_dir"/*.ttc 2>/dev/null | sort || true)
if [[ -z "$files" ]]; then
    emit_empty
    exit 0
fi

# Header: types + lookup table. Mac/Linux references the .S file's
# extern symbols and uses a const table; Windows starts with NULL
# data and fills it at startup from compiled-in .rc resources.
{
    echo "/* AUTO-GENERATED by tools/gen_fonts.sh — do not edit. */"
    echo "#pragma once"
    echo "#include <stddef.h>"
    echo
    echo "typedef struct {"
    echo "    const char *name;"
    echo "    const char *ext;            /* \"ttf\" / \"otf\" / \"ttc\" */"
    echo "    const unsigned char *data;"
    echo "    unsigned int data_size;"
    echo "} EmbeddedFont;"
    echo
    echo "#ifdef _WIN32"
    echo "/* On Windows the data pointers are filled at runtime by"
    echo "   embedded_fonts_init() (defined in fonts_embedded_win.c)"
    echo "   from RCDATA resources baked in via fonts_embedded.rc."
    echo "   The array is declared extern here and DEFINED in"
    echo "   fonts_embedded_win.c — if it were 'static' in the"
    echo "   header, every translation unit would get its own"
    echo "   private copy, init would write to one, and main.c"
    echo "   would read from another (always-NULL) one. */"
    echo "extern EmbeddedFont k_embedded_fonts[];"
    echo "extern const int k_embedded_font_count;"
    echo "void embedded_fonts_init(void);"
    echo "#else"
    for f in $files; do
        ident="$(c_ident "$f")"
        echo "extern const unsigned char rbterm_font_${ident}_start[];"
    done
    echo
    echo "static const EmbeddedFont k_embedded_fonts[] = {"
    for f in $files; do
        ident="$(c_ident "$f")"
        name="$(display_name "$f")"
        ext_raw="${f##*.}"
        ext_lower="$(echo "$ext_raw" | tr '[:upper:]' '[:lower:]')"
        size=$(wc -c < "$f" | tr -d ' ')
        printf '    {"%s", "%s", rbterm_font_%s_start, %su},\n' \
            "$name" "$ext_lower" "$ident" "$size"
    done
    echo "};"
    echo "static const int k_embedded_font_count ="
    echo "    (int)(sizeof(k_embedded_fonts) / sizeof(k_embedded_fonts[0]));"
    echo "static inline void embedded_fonts_init(void) {}"
    echo "#endif"
} > "$out_h"

# Assembly: .incbin each font with start/end labels around it. .const
# section keeps the data read-only on Mach-O; on ELF the default
# .rodata is fine.
{
    echo "/* AUTO-GENERATED by tools/gen_fonts.sh — do not edit. */"
    case "$(uname -s)" in
        Darwin) echo ".section __TEXT,__const" ;;
        *)      echo ".section .rodata"        ;;
    esac
    for f in $files; do
        ident="$(c_ident "$f")"
        # Absolute path so the assembler's CWD doesn't matter.
        abs="$(cd "$(dirname "$f")" && pwd)/$(basename "$f")"
        echo ".p2align 4"
        echo ".global ${sym_pfx}rbterm_font_${ident}_start"
        echo "${sym_pfx}rbterm_font_${ident}_start:"
        echo ".incbin \"${abs}\""
        echo ".global ${sym_pfx}rbterm_font_${ident}_end"
        echo "${sym_pfx}rbterm_font_${ident}_end:"
    done
} > "$out_s"

# Windows resource script — one RCDATA per font with a sequential
# integer ID. The RC compiler bundles the binary into the .exe;
# embedded_fonts_init() at runtime (fonts_embedded_win.c) calls
# FindResource / LoadResource to recover the bytes.
#
# Paths are emitted RELATIVE to the .rc file's location (src/) so
# they don't bake in absolute paths from the dev box and so we don't
# have to deal with Git Bash's `/d/a/...` style on Windows runners
# (which RC.exe can't resolve). The .rc file lives in src/, fonts
# live in assets/fonts/, so the relative prefix is "../assets/fonts/".
{
    echo "/* AUTO-GENERATED by tools/gen_fonts.sh — do not edit. */"
    rcid=1000
    for f in $files; do
        base=$(basename "$f")
        echo "${rcid} RBTERMFONT \"../${src_dir}/${base}\""
        rcid=$((rcid + 1))
    done
} > "$out_rc"

# Companion C file for Windows: defines embedded_fonts_init() which
# walks the resource table and populates k_embedded_fonts[i].data /
# data_size pointers. Order in the rc file matches the order in
# fonts_embedded.h's Windows table, so we just zip them together.
{
    echo "/* AUTO-GENERATED by tools/gen_fonts.sh — do not edit. */"
    echo "#ifdef _WIN32"
    echo "/* Don't strip NOUSER here — MAKEINTRESOURCEA + the rest of the"
    echo "   resource API live in winuser.h. NOGDI is fine to keep. */"
    echo "#define WIN32_LEAN_AND_MEAN"
    echo "#define NOGDI"
    echo "#include <windows.h>"
    echo "#include \"fonts_embedded.h\""
    echo
    echo "/* Definition lives here (not the header) so every TU that"
    echo "   includes fonts_embedded.h shares the SAME array — otherwise"
    echo "   each TU gets its own static copy and embedded_fonts_init's"
    echo "   writes never reach main.c's reads. */"
    echo "EmbeddedFont k_embedded_fonts[] = {"
    for f in $files; do
        name="$(display_name "$f")"
        ext_raw="${f##*.}"
        ext_lower="$(echo "$ext_raw" | tr '[:upper:]' '[:lower:]')"
        printf '    {"%s", "%s", NULL, 0u},\n' "$name" "$ext_lower"
    done
    echo "};"
    echo "const int k_embedded_font_count ="
    echo "    (int)(sizeof(k_embedded_fonts) / sizeof(k_embedded_fonts[0]));"
    echo
    echo "void embedded_fonts_init(void) {"
    echo "    HMODULE mod = GetModuleHandleW(NULL);"
    rcid=1000
    i=0
    for f in $files; do
        echo "    {"
        echo "        HRSRC h = FindResourceA(mod, MAKEINTRESOURCEA(${rcid}), \"RBTERMFONT\");"
        echo "        if (h) {"
        echo "            HGLOBAL g = LoadResource(mod, h);"
        echo "            DWORD sz = SizeofResource(mod, h);"
        echo "            void *p = LockResource(g);"
        echo "            if (p && sz > 0) {"
        echo "                k_embedded_fonts[${i}].data = (const unsigned char *)p;"
        echo "                k_embedded_fonts[${i}].data_size = (unsigned int)sz;"
        echo "            }"
        echo "        }"
        echo "    }"
        rcid=$((rcid + 1))
        i=$((i + 1))
    done
    echo "}"
    echo "#endif /* _WIN32 */"
} > "$out_winc"

echo "gen_fonts.sh: wrote $out_h + $out_s + $out_rc + $out_winc ($(echo "$files" | wc -l | tr -d ' ') fonts)"
