#!/usr/bin/env bash
# Bundle every .ttf / .otf / .ttc in assets/fonts/ into the binary so
# the exe is self-contained — no `fonts/` folder needed at runtime.
#
# Approach: emit a tiny .S file that uses `.incbin` to pull each font
# into the .rodata section, exposing start/end symbols. A matching .h
# declares the symbols and lists each font for the picker. This is far
# cheaper to compile than a 13MB hex-encoded C array (a single .incbin
# is ~instant; a hex array is multi-megabyte text the preprocessor has
# to parse).
#
# Per-font symbols:
#   _rbterm_font_<ident>_start    (data pointer)
#   _rbterm_font_<ident>_end      (one-past-the-end pointer)
# Display names strip the extension and any -Regular suffix.
set -euo pipefail
src_dir="${1:-assets/fonts}"
out_h="${2:-src/fonts_embedded.h}"
out_s="${3:-src/fonts_embedded.S}"

emit_empty() {
    cat > "$out_h" <<'EOF'
/* AUTO-GENERATED by tools/gen_fonts.sh (no fonts present). */
#pragma once
typedef struct {
    const char *name;
    const char *ext;            /* "ttf" / "otf" / "ttc" */
    const unsigned char *data;
    unsigned int data_size;
} EmbeddedFont;
static const EmbeddedFont k_embedded_fonts[1] = { {"", "", 0, 0} };
static const int k_embedded_font_count = 0;
EOF
    cat > "$out_s" <<'EOF'
/* AUTO-GENERATED by tools/gen_fonts.sh (no fonts present). */
EOF
}

if [[ ! -d "$src_dir" ]]; then
    emit_empty
    exit 0
fi

display_name() {
    local f="$1"
    f="${f##*/}"
    f="${f%.[oOtT][tT][fFcC]}"
    f="${f%-Regular}"
    f="${f%-regular}"
    echo "$f"
}

c_ident() {
    local f
    f=$(basename "$1")
    echo "${f//[^A-Za-z0-9]/_}"
}

# Apple's clang assembler prefixes C globals with an underscore on
# Mach-O; on ELF (Linux) it doesn't. We emit the macro-friendly form
# and let the assembler / linker resolve.
case "$(uname -s)" in
    Darwin) sym_pfx="_" ;;
    *)      sym_pfx=""  ;;
esac

# Collect files in stable order.
files=$(ls "$src_dir"/*.ttf "$src_dir"/*.otf "$src_dir"/*.ttc 2>/dev/null | sort || true)
if [[ -z "$files" ]]; then
    emit_empty
    exit 0
fi

# Header: extern declarations + lookup table.
{
    echo "/* AUTO-GENERATED by tools/gen_fonts.sh — do not edit. */"
    echo "#pragma once"
    echo "#include <stddef.h>"
    echo
    echo "typedef struct {"
    echo "    const char *name;"
    echo "    const char *ext;            /* \"ttf\" / \"otf\" / \"ttc\" */"
    echo "    const unsigned char *data;"
    echo "    unsigned int data_size;"
    echo "} EmbeddedFont;"
    echo
    for f in $files; do
        ident="$(c_ident "$f")"
        echo "extern const unsigned char rbterm_font_${ident}_start[];"
    done
    echo
    echo "static const EmbeddedFont k_embedded_fonts[] = {"
    for f in $files; do
        ident="$(c_ident "$f")"
        name="$(display_name "$f")"
        ext_raw="${f##*.}"
        ext_lower="$(echo "$ext_raw" | tr '[:upper:]' '[:lower:]')"
        # Use literal byte counts so the static initializer is a
        # compile-time constant (pointer subtraction between two
        # extern symbols isn't, even though the linker resolves it).
        size=$(wc -c < "$f" | tr -d ' ')
        printf '    {"%s", "%s", rbterm_font_%s_start, %su},\n' \
            "$name" "$ext_lower" "$ident" "$size"
    done
    echo "};"
    echo "static const int k_embedded_font_count ="
    echo "    (int)(sizeof(k_embedded_fonts) / sizeof(k_embedded_fonts[0]));"
} > "$out_h"

# Assembly: .incbin each font with start/end labels around it. .const
# section keeps the data read-only on Mach-O; on ELF the default
# .rodata is fine.
{
    echo "/* AUTO-GENERATED by tools/gen_fonts.sh — do not edit. */"
    case "$(uname -s)" in
        Darwin) echo ".section __TEXT,__const" ;;
        *)      echo ".section .rodata"        ;;
    esac
    for f in $files; do
        ident="$(c_ident "$f")"
        # Absolute path so the assembler's CWD doesn't matter.
        abs="$(cd "$(dirname "$f")" && pwd)/$(basename "$f")"
        echo ".p2align 4"
        echo ".global ${sym_pfx}rbterm_font_${ident}_start"
        echo "${sym_pfx}rbterm_font_${ident}_start:"
        echo ".incbin \"${abs}\""
        echo ".global ${sym_pfx}rbterm_font_${ident}_end"
        echo "${sym_pfx}rbterm_font_${ident}_end:"
    done
} > "$out_s"

echo "gen_fonts.sh: wrote $out_h + $out_s ($(echo "$files" | wc -l | tr -d ' ') fonts)"
