#!/usr/bin/env bash
# Turn every kfc/dark/* palette file from the pal submodule into a C
# string-literal entry in src/themes_embedded.h. Each theme file is the
# `key=value` format (background= / foreground= / cursor= / color00..15=).
# We don't parse them here — that happens at runtime in theme.c. This
# script just packages the raw bodies alongside their filenames so the
# terminal can work offline without the submodule being present at
# runtime.
set -euo pipefail
src_dir="${1:-third_party/pal/palettes/kfc/dark}"
out_file="${2:-src/themes_embedded.h}"

if [[ ! -d "$src_dir" ]]; then
  echo "gen_themes.sh: $src_dir missing — did you init the submodule? (git submodule update --init)" >&2
  # Emit an empty header so the build still succeeds.
  cat > "$out_file" <<'EOF'
/* AUTO-GENERATED by tools/gen_themes.sh (no themes — submodule absent). */
#pragma once
typedef struct { const char *name; const char *body; } EmbeddedTheme;
static const EmbeddedTheme k_embedded_themes[1] = { {"", ""} };
static const int k_embedded_theme_count = 0;
EOF
  exit 0
fi

{
  echo "/* AUTO-GENERATED by tools/gen_themes.sh — do not edit by hand. */"
  echo "#pragma once"
  echo "typedef struct { const char *name; const char *body; } EmbeddedTheme;"
  echo "static const EmbeddedTheme k_embedded_themes[] = {"
  for f in "$src_dir"/*; do
    [ -f "$f" ] || continue
    name=$(basename "$f")
    # Escape backslashes first, then double quotes, then fold newlines
    # into a literal \n so the body fits on one C string line.
    body=$(sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' "$f" \
           | awk 'BEGIN{ORS=""} {print $0 "\\n"}')
    printf '    {"%s", "%s"},\n' "$name" "$body"
  done
  echo "};"
  echo "static const int k_embedded_theme_count ="
  echo "    (int)(sizeof(k_embedded_themes) / sizeof(k_embedded_themes[0]));"
} > "$out_file"
echo "gen_themes.sh: wrote $out_file ($(wc -l < "$out_file" | tr -d ' ') lines)"
